---
- name: CHECK VERSION, INTERFACES AND CLEAR COUNTERS
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
   - name: run show version
     cisco.ios.ios_command:
       commands: show version

   - name: run show interfaces
     cisco.ios.ios_command:
       commands: show interfaces


   - name: run commands that require answering a prompt
     cisco.ios.ios_command:
       commands:
       - command: clear counters GigabitEthernet 1
         prompt: Clear "show interface" counters on this interface \[confirm\]
         answer: c 

       

